# Generated by Django 4.1.2 on 2022-11-12 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_passwordreset"),
    ]

    operations = [
        migrations.RemoveField(model_name="passwordreset", name="user",),
        migrations.AddField(
            model_name="passwordreset",
            name="email",
            field=models.EmailField(
                default=datetime.datetime(
                    2022, 11, 12, 17, 0, 53, 728435, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
