# Generated by Django 4.1.2 on 2022-11-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction", name="ref", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
